services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4200:4200" # Map container port 4200 to host port 4200
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  backend_api:
    image: node:20-bullseye
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: npx nx serve aignostic

