services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    image: node:lts
    volumes:
      - .:/app
    working_dir: /app
    command: npx nx serve frontend --host 0.0.0.0
    ports:
      - '4200:4200'
