services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    image: node:lts
    volumes:
      - .:/app
    working_dir: /app
    command: npx nx serve frontend --host 0.0.0.0
    ports:
      - '4200:4200'
  backend:
    build:
      context: .
      dockerfile: ./aignostic/Dockerfile.dev
    volumes:
      - .:/app
    command: npx nx serve aignostic --host 0.0.0.0
    working_dir: /app
    ports:
      - '8000:8000'
# volumes:
#   venv:
