version: '3.8'
services:
  ###
  # Backend services
  ###
  # Api Router
  api_router:
    container_name: api_router
    image: ghcr.io/aignostic/api:latest
    ports:
      - '8000:8000'
    networks:
      - aignostic_network
    environment:
      - RABBITMQ_HOST=rabbitmq

  # Microservices
  worker_ms:
    container_name: worker
    image: ghcr.io/aignostic/worker:latest
    deploy:
      replicas: 3
    networks:
      - aignostic_network
    environment:
      - RABBITMQ_HOST=rabbitmq

  aggregator_ms:
    container_name: aggregator
    image: ghcr.io/aignostic/aggregator:latest
    networks:
      - aignostic_network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - GOOGLE_API_KEY_FILE=/run/secrets/google_ai_api_key
    secrets:
      - google_ai_api_key # Google AI API key

  # Reverse proxy
  reverse_proxy:
    image: ghcr.io/aignostic/nginx_reverse_proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/aignostic-api.docsoc.co.uk/fullchain.pem:/opt/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/aignostic-api.docsoc.co.uk/privkey.pem:/opt/nginx/certs/privkey.key
    networks:
      - aignostic_network
    depends_on:
      - api_router

  user_added_metrics:
    container_name: user_added_metrics
    image: ghcr.io/aignostic/useraddedmetrics:latest
    networks:
      - aignostic_network
    environment:
      - RABBITMQ_HOST=rabbitmq

networks:
  aignostic_network:
    driver: overlay
    attachable: true
    name: aignostic

secrets:
  google_ai_api_key:
    external: true
