services:
  ###
  # Backend services
  ###
  # Api Router
  api_router:
    container_name: api_router
    image: ghcr.io/aignostic/api:latest
    ports:
      - '8000:8000'
    networks:
      - aignostic_network
    environment:
      - RABBITMQ_HOST=rabbitmq

  # Microservices
  worker_ms:
    container_name: worker
    image: ghcr.io/aignostic/worker:latest
    deploy:
      replicas: 3
    networks:
      - aignostic_network
    environment:
      - RABBITMQ_HOST=rabbitmq

  aggregator_ms:
    container_name: aggregator
    image: ghcr.io/aignostic/aggregator:latest
    networks:
      - aignostic_network
    environment:
      - RABBITMQ_HOST=rabbitmq

networks:
  aignostic_network:
    driver: overlay
    attachable: true
    name: aignostic
