version: '3.8'

services:
  ###
  # Services
  ###
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - aignostic_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=securepassword
  redis:
    image: redis
    networks:
      - aignostic_network
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  aignostic_network:
    name: aignostic
    external: true
