[tool.coverage.run]
branch = true
source = ["api"]

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:"]
show_missing = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = "--cov --cov-report html:'../../coverage/api/html' --cov-report xml:'../../coverage/api/coverage.xml' --html='../../reports/api/unittests/html/index.html' --junitxml='../../reports/api/unittests/junit.xml'"

[tool.poetry]
name = "api"
version = "1.0.0"
description = "AIgnostic Risk Monitoring and Auditing"
authors = []
license = "Proprietary"
readme = "README.md"

[[tool.poetry.packages]]
include = "api"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
numpy = "^2.2.1"
pydantic = "^2.10.5"
uvicorn = "^0.34.0"
pandas = "^2.2.3"
types-requests = "^2.32.0.20241016"
pandas-stubs = "^2.2.3.241126"
pytest = "^8.3.4"
pytest-asyncio = "^0.25.2"
update = "^0.0.1"
pika = "^1.3.2"
requests = "^2.32.3"
aif360 = "^0.6.1"
websockets = "^14.2"

[tool.poetry.dependencies.fastapi]
extras = ["standard"]
version = "^0.115.6"

[tool.poetry.dependencies.metrics]
path = "../metrics"
develop = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
