[tool.coverage.run]
branch = true
source = [ "common" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'../../coverage/common/html' --cov-report xml:'../../coverage/common/coverage.xml' --html='../../reports/common/unittests/html/index.html' --junitxml='../../reports/common/unittests/junit.xml'"

[tool.poetry]
name = "common"
version = "1.0.0"
description = "Pydantic models shared by everything"
authors = [ ]
license = "Proprietary"
readme = "README.md"
group = { }

  [[tool.poetry.packages]]
  include = "common"

  [tool.poetry.dependencies]
  python = ">=3.12,<3.13"
  pydantic = "^2.10.6"
  pika = "^1.3.2"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
