# property_to_regulations = {
#     "adversarial robustness": ["article 15"],
#     "explainability": ["article 13",
#                        "article 14 (4c)"],
#     "fairness": ["article 10",
#                  "article 15"],
#     "uncertainity": ["article 13"],
#     "privacy": ["article 2"],
#     "data minimality": ["article 10"],
# }
property_to_regulations = {
    "adversarial robustness": ["15"],
    "explainability": ["13",
                       "14"],
    "fairness": ["10",
                 "15"],
    "uncertainity": ["13"],
    "privacy": ["2"],
    "data minimality": ["10"],
}

property_to_metrics = {
    "adversarial robustness": ["fast gradient sign method",
                               "projected gradient descent"],
    "explainability": ["gradient explanations",
                       "LIME",
                       "SHAP",
                       "identified feature importance",
                       "explanation alignment"],
    "fairness": ["equal opportunity difference",
                 "disparate impact",
                 "statistical parity difference",
                 "false negative rate difference",
                 "true positive rate difference",
                 "equalized odds difference",
                 "negative predictive value",
                 "positive predictive value"],
    "uncertainity": ["OOD",
                     "roc auc"],
    "privacy": ["prediction privacy scores"],
    "data minimality": ["from paper"],
}
