[tool.coverage.run]
branch = true
source = ["llm_insights"]

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:"]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'../../coverage/llm_insights/html' --cov-report xml:'../../coverage/llm_insights/coverage.xml' --html='../../reports/llm_insights/unittests/html/index.html' --junitxml='../../reports/llm_insights/unittests/junit.xml'"

[tool.poetry]
name = "llm-insights"
version = "1.0.0"
description = "LLM Insights"
authors = []
license = "Proprietary"
readme = "README.md"

[[tool.poetry.packages]]
include = "llm_insights"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
langchain-google-genai = "^2.0.9"
langchain-core = "^0.3.36"

[tool.poetry.dependencies.common]
path = "../common"
develop = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
